#!/bin/sh
#
# oops-conf
#
# This file shows some examples of calling configure
# script for various compilers/OS.
#

case $1 in

acc)
    # AIX cc (3.6.5, 4.4, 5.0)
    CC="xlc_r  -O2"
    CXX="xlC_r -O2"
    CPPFLAGS="-I/usr/include"
    CFLAGS="-I/usr/include"
    LDFLAGS=""
    ;;

scc)
    # Solaris cc (SUN Workshop 5.0, Forte C 6U1)
    CC="cc -fast -xO3"
    CPPFLAGS="-I/usr/include -I/usr/local/include"
    CFLAGS="-I/usr/include -I/usr/local/include"
    LDFLAGS="-L/usr/local/lib"
    ;;

gcc)
    # gcc (2.8.1, 2.95.2)
    CC=gcc
    CFLAGS="-O2 -Wall"
    ;;

*)
    echo "Usage: oops-conf [option]"
    echo "       option:"
    echo "          acc   - IBM C for AIX 3.6.5, 4.4, 5.0"
    echo "          scc   - SUN Workshop 5.0, Forte C 6U1"
    echo "          gcc   - GNU C"
    exit 0
    ;;

esac


CC="$CC" \
CXX="$CXX" \
CPPFLAGS="$CPPFLAGS" \
CFLAGS="$CFLAGS" \
LDFLAGS="$LDFLAGS" \
./configure \
    --prefix=/opt/local \
    --enable-large-files \
    --enable-oops-user=oops \
    --with-LDAP=/usr/ldap
